//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetupWarehouseAdapter.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SetupWarehouseAdapter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created and scheduled custom job {0} with the exension {1}..
        /// </summary>
        internal static string CreatedJob {
            get {
                return ResourceManager.GetString("CreatedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A job with the name {0} already exists.  Delete the job and recreate it to change its.
        /// </summary>
        internal static string JobAlreadyExists {
            get {
                return ResourceManager.GetString("JobAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job with the name {0} was deleted..
        /// </summary>
        internal static string JobDeleted {
            get {
                return ResourceManager.GetString("JobDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No job with the name {0} was found.  No jobs were deleted..
        /// </summary>
        internal static string JobNotFound {
            get {
                return ResourceManager.GetString("JobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetupCustomAdapter [-c] [-d] [-t] -JobName=&lt;Job Name&gt; -SyncJobExtension=&lt;Sync Job Extension&gt; -Collection=&lt;TFS Collection URI&gt;
        ///
        ///[-c] Instala o job do Adapter
        ///[-d] Remove o job do Adapter
        ///[-t] Tempo de intervalo (em minutos) entre as execuções do serviço (por padrão, 2 minutos)
        ///
        ///-JobName=&quot;TFS Usage Log&quot; (Nome amigável do adapter)
        ///-SyncJobExtension={Namespace}.{WarehouseSyncJobExtension class name}
        ///-Collection=http://vsalm:8080/tfs/DefaultCollection
        ///
        ///.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
